name: Check broken links

on:
  workflow_dispatch:
  schedule:
    - cron: "00 18 */4 * *"

jobs:
  generate_md_file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'latest'

      - name: Generate md file
        run: node .github/generate-md-file.js

      - name: Link Checker
        id: lychee
        uses: lycheeverse/lychee-action@v1
        with:
          args: --no-progress '.github/output.md' --exclude-mail --exclude 'https://pixabay.com/*' --exclude 'https://www.pexels.com/*' --exclude 'https://svgl.vercel.app/' --exclude "https://help.videvo.net/*" --exclude 'https://remixicon.com/license' --exclude 'flaticon.com/*' --exclude 'https://www.artstation.com/' --exclude 'https://archetypeapp.com' --exclude 'https://github.com/chakra-ui/ark/*' --exclude 'https://medium.com'

      - name: Create Issue From File
        if: env.lychee_exit_code != 0
        uses: peter-evans/create-issue-from-file@v4
        with:
          title: Link Checker Report
          content-filepath: ./lychee/out.md
          labels: report, automated issue